### ISSUE TITLE
[Bug] Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by ricardojfc** [skills/communicate-using-markdown#39]
**Describe the bug**
When I copied the repo, I got a mail with this subject: Run failed: Step 0, Start - main (6cd1112)

**To Reproduce**
1. Go to https://github.com/skills/communicate-using-markdown
2. Click on 'Use this template -> Create new repository'
3. Create a public repository under my namespace
4. I got an email with the subject above.

**Expected behavior**
The workflow shouldn't fail

**Screenshots**

![Screenshot 2023-02-10 at 3 20 58 PM](https://user-images.githubusercontent.com/112181786/218115050-58a371f0-b3df-4b7a-88f9-0e272417638c.png)

**Device information**
 - Type: laptop
 - OS: macos 13.1
 - Browser chrome
 - Version 110.0.5481.77 (Official Build) (arm64)

**Comment by heiskr** [comment]
Thank you for the bug report. This error seems to be appearing recently on a number of courses, and data-wise it looks like an increasing number of users. I will escalate this internally to the appropriate teams.

**Comment by sinsukehlab** [comment]
This error is related to a recent update on the default GITHUB_TOKEN permissions.
https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/

I found this restriction circumvented when I create a repository using skills/release-based-workflow as the template. This is probably because 0-start.yml in skills/release-based-workflow runs a shell script instead of directly coded commands.

**Comment by heiskr** [comment]
Thank you for opening this issue. We have updated this course to remove automatically creating pull requests. Please let us know if you continue to experience errors in this course.
