### ISSUE TITLE
[Bug] Step 1, stuck with "Resolve Conflicts

### ISSUE THREAD

**Issue by sergefonville** [skills/communicate-using-markdown#81]
In attempting to execute step 1, it does not execute `On commit, start markdown, headers`

It should execute the action after '20 seconds'. Having waited 5 minutes, I checked the pull request and opend `Start markdown` It did not execute `On commit, start markdown, headers`.  Below the list of steps it states: "This branch has conflicts that must be resolved"
When looking at the conflicts `.github/steps/-step.txt` contains:
```
<<<<<<< start-markdown
# 1
=======
1
>>>>>>> main
```

None of this is part of the steps I should execute.

What can I do to resolve/prevent this?

**Comment by sergefonville** [comment]
Perhaps it is related to either a step missing between 4 and 5 below the activity `Edit your file with headers`, since `Click Pull Request` needs to be clicked twice or in step 9 the message is not visible until after I click `Commit Changes`. Both of these seem to be irrelevant to the issue of the merge conflict though.

**Comment by hectorsector** [comment]
👋 @sergefonville, you may want to look into [resolving merge conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts). Merge conflicts can occur when working with Git and GitHub, but it is not an inherent bug in the course. I will close this issue since the course doesn't contain a bug, but feel free to read through the docs I linked, ask for help in the [course discussion](https://github.com/orgs/skills/discussions/categories/communicate-using-markdown), or reopen if you believe there's truly a bug with the course.

**Comment by hectorsector** [comment]
Actually, I want to correct what I said, you're absolutely right that the file you linked should contain no conflicts (and you probably didn't touch it). I can look deeper into this if you can provide me a link to your repository. Thanks!

**Comment by sergefonville** [comment]
My repository is https://github.com/sergefonville/skills-communicate-using-markdown, however it works as expected. Without any issue it is now at `Step 2: Add an image`. Not sure why it is working now.

**Comment by hectorsector** [comment]
Thanks for following up. I'll keep this issue closed since it resolved itself but we can always come back to it if it resurfaces.
